// Turns the E2E screenshots (e2e/screenshots, regenerated by `npm run test:e2e`) into light WebP
// copies for the README in docs/screenshots. Full-page captures are cut to their first screens.
import sharp from "sharp";
import { mkdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const src = path.join(root, "e2e", "screenshots");
const out = path.join(root, "docs", "screenshots");
await mkdir(out, { recursive: true });

// file -> height (in source pixels) to keep from the top; null keeps the whole image
const PICKS = {
  "desktop-hero-laguna.png": null,
  "desktop-hero-noturno.png": null,
  "desktop-hero-mochi.png": null,
  "desktop-hero-matcha.png": null,
  "desktop-hero-sinal.png": null,
  "desktop-loja.png": 1400,
  "desktop-produto-folk-75.png": 1400,
  "mobile-home.png": 2600,
  "mobile-checkout.png": 2600,
};

for (const [file, keep] of Object.entries(PICKS)) {
  const mobile = file.startsWith("mobile");
  let img = sharp(path.join(src, file));
  const { width, height } = await img.metadata();
  if (keep && height > keep) img = img.extract({ left: 0, top: 0, width, height: keep });
  const target = path.join(out, file.replace(/\.png$/, ".webp"));
  const info = await img
    .resize({ width: mobile ? 540 : 1600, withoutEnlargement: true })
    .webp({ quality: 80, effort: 6 })
    .toFile(target);
  console.log(path.basename(target), `${Math.round(info.size / 1024)} KB`);
}
